### ISSUE TITLE
ListField problem

### ISSUE THREAD

**Issue by ksobolewski-netins** [rstgroup/react-components-form#12]
There are two problems with ListField form element.
Described with book from demo version.

First:

1. Fill author one
2. Add new author
3. Remove first author

New(empty) author has been removed.

Second:

1. Fill author 1
2. Add and fill new author
3. Remove author 1
4. Add and fill new author
5. Add new author
6. Remove first author

First author has been removed, but new(empty) author gets second data.

**Comment by mprzodala** [comment]
I will work on this. This issue is only on ObjectField.

**Comment by mprzodala** [comment]
Issue resolved in version v1.8.6 please check.
