### ISSUE TITLE
Why not `<form/>`

### ISSUE THREAD

**Issue by auser** [rstgroup/react-components-form#16]
Out of curiosity, why is the `<Form />` component surrounded by `<div />` rather than `<form />`?

With `<form />`, we can have a press-enter-to-submit style form, whereas with `<div />` we must click to submit. Is this an oversight?

**Comment by mprzodala** [comment]
I will add form tag in next version (v2.1.0). I was use only div becaus I need sometime subforms. I will add flag "subform" it will be false by default so you will be have form tag by defalt :) . Thanks for info.

**Comment by auser** [comment]
Any idea of release date?

**Comment by auser** [comment]
Day* (autocorrect)

**Comment by mprzodala** [comment]
New version avaible. Please give me know if you will see any issues.
