### ISSUE TITLE
onSubmit is called twice

### ISSUE THREAD

**Issue by marcinwysocki** [rstgroup/react-components-form#19]
`onSubmit` handler passed as a prop to the `Form` component is called twice. It's caused by `this.submitForm` being passed to children via context, and then called [here](https://github.com/mprzodala/react-components-form/blob/master/src/components/FieldConnect.jsx#L74), apart from the [submit handler](https://github.com/mprzodala/react-components-form/blob/v2.1.0/src/components/Form.jsx#L122) in `Form` class itself.

It's related to changes in `v2.1.0`. I can submit a PR to fix that, probably tomorrow.

**Comment by marcinwysocki** [comment]
I've submitted #21 with a fix for this.

**Comment by mprzodala** [comment]
Fix merged. Thanks for pull request :)
