### ISSUE TITLE
Where are the radio's ? 

### ISSUE THREAD

**Issue by leroy0211** [rstgroup/react-components-form#40]
I was looking for a Radio component, but it looks to me that one doesn't exist. Am I missing something?

**Comment by mprzodala** [comment]
Radio button missing :) I will add it later. So you can create pull request with RadioFiled or wait for my pull request :)

**Comment by leroy0211** [comment]
What do think about instead of creating a `RadioField`, you create a `ChoiceField` with 2 props `expanded` and `multiple`. 

These 2 properties will determine if it's a `select` field, a `multiple select` field, a set of `radio's` or a set of `checkboxes`. 
And by default it's a Select field.

Examples:

```
const countries = [
    {label:'Poland', value:'PL'},
    {label:'Germany', value:'DE'},
    {label:'England', value:'EN'}
];

# Select field
<ChoiceField name="question" options={countries} />

# Multiple select field
<ChoiceField name="question" options={countries} multiple={true}  />

# Radio's
<ChoiceField name="question" options={countries} expanded={true}  />

# Checkboxes
<ChoiceField name="question" options={countries} multiple={true} expanded={true}  />

``` 

FYI: Based on Symfony [ChoiceType](http://symfony.com/doc/current/reference/forms/types/choice.html#select-tag-checkboxes-or-radio-buttons)

**Comment by mprzodala** [comment]
RadioField added
