### ISSUE TITLE
TypeError: this.updater.enqueueCallback is not a function

### ISSUE THREAD

**Issue by vteraz** [rstgroup/react-components-form#49]
Hi. I`m using react-components-form with "react": "16.0.0" and have such error:

`TypeError: this.updater.enqueueCallback is not a function
./node_modules/react-components-form/main.js/</</n.prototype.setState
node_modules/react-components-form/main.js:11
`

Can you help with that?

**Comment by mprzodala** [comment]
Hi @valedelobo I was migrate react-components-form to react 16.0.0 in version 3.1.0. Please check and give me know.
