### ISSUE TITLE
_reactComponentsForm.FormEventsEmitter is not a constructor

### ISSUE THREAD

**Issue by Lianleli** [rstgroup/react-components-form#54]
```
import { FormEventsEmitter } from 'react-components-form';

const eventsEmitter = new FormEventsEmitter();
```

throws an error: 
`Uncaught TypeError: _reactComponentsForm.FormEventsEmitter is not a constructor`

**Comment by mprzodala** [comment]
What version of react-components-form you have?

**Comment by Lianleli** [comment]
It's my fault, I was looking at the 3.0.0 documentation and i had 2.11.3 installed.
