### ISSUE TITLE
Incorrect listener name in documentation

### ISSUE THREAD

**Issue by matcake** [rstgroup/react-components-form#65]
Hi,
FormEventsEmitter documentation contains information about `changeModel` listener name. But there is in the code `modelChange` (https://github.com/rstgroup/react-components-form/blob/master/src/components/FieldConnect.jsx#L58).

Please update docs :)

**Comment by mprzodala** [comment]
@mplacekCS thank you for this information. Event name is changed. Please give me know if you will find other issue.
