### ISSUE TITLE
ListField and errors handling

### ISSUE THREAD

**Issue by Wolvie** [rstgroup/react-components-form#82]
There is a problem with error handling in Listfield, example:

https://codesandbox.io/s/infallible-hill-iqdxi

`validationErrors` is NOT EMPTY but `hasValidationError` is FALSE

**Comment by mprzodala** [comment]
@Wolvie Please check new version 3.8.1 and let me know it's works fine.
https://codesandbox.io/s/shy-flower-nlehy
